# Generated by Django 5.0.2 on 2024-02-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="images",
        ),
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
    ]
