FROM node:15 as builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY ./public /usr/src/app/public
COPY ./src /usr/src/app/src

RUN npm run build

FROM nginx:1.15.10-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]