# Generated by Django 5.0.2 on 2024-02-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="purchaser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="purchasers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
