# Generated by Django 5.0.2 on 2024-02-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="seller",
        ),
    ]
