# Generated by Django 5.0.2 on 2024-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_1",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
