# Generated by Django 5.0.2 on 2024-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_image_1_alter_post_image_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_1",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
