# Generated by Django 5.0.2 on 2024-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_1",
            field=models.ImageField(upload_to="static/images"),
        ),
    ]
